version: '3.8'

networks:
  default:
    name: n8n_default
    external: true

services:
  ticket-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket-app-prod
    restart: unless-stopped
    ports:
      - "3005:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ticketapp.rule=Host(`tiquetera.ktuche.com`)"
      - "traefik.http.routers.ticketapp.entrypoints=websecure"
      - "traefik.http.routers.ticketapp.tls.certresolver=mytlschallenge"
      - "traefik.http.services.ticketapp.loadbalancer.server.port=3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
