"use client";

import { useState } from "react";
import { criarOperador, removerOperador } from "./actions";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetFooter,
} from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Card, CardContent } from "@/components/ui/card";

interface Membro {
  id: string;
  auth_id: string;
  nombre: string;
  rol: string;
  email?: string;
}

interface EquipeClientProps {
  equipeInicial: Membro[];
}

export default function EquipeClient({ equipeInicial }: EquipeClientProps) {
  const [equipe, setEquipe] = useState<Membro[]>(equipeInicial);
  const [isSheetOpen, setIsSheetOpen] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");

  const handleCreate = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setErrorMsg("");
    setIsSubmitting(true);

    const formData = new FormData(e.currentTarget);
    const nombre = formData.get("nombre") as string;
    const email = formData.get("email") as string;
    const rol = formData.get("rol") as string;

    const res = await criarOperador(formData);

    if (res.error) {
      setErrorMsg(res.error);
      setIsSubmitting(false);
      return;
    }

    // Refresh would be best here via router.refresh(), but we can optimistic update
    // Note: Since auth_id is generated by supabase, an exact optimistic update is hard without reloading
    // We will just reload the page to get the fresh data
    window.location.reload();
  };

  const handleRemove = async (authId: string, nombre: string) => {
    if (!confirm(`¿Estás seguro de que deseas eliminar permanentemente a ${nombre}?`)) return;
    
    const res = await removerOperador(authId);
    if (res.error) {
      alert(`Error: ${res.error}`);
      return;
    }

    setEquipe(equipe.filter(m => m.auth_id !== authId));
  };

  return (
    <>
      <div className="flex justify-between items-center mb-8">
        <div>
          <h1 className="text-3xl font-black text-secondary tracking-tight">
            Gestión de Equipo
          </h1>
          <p className="text-muted font-medium mt-1">
            Administra accesos y operadores del sistema
          </p>
        </div>
        <Button 
          onClick={() => setIsSheetOpen(true)}
          className="bg-primary hover:bg-primary-dark text-white font-bold py-3 px-6 rounded-2xl shadow-lg border-2 border-primary/20 hover:-translate-y-1 transition-all"
        >
          <span className="mr-2 text-xl">+</span> Nuevo Operador
        </Button>
      </div>

      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {equipe.map((membro) => (
          <Card key={membro.id} className="relative overflow-hidden group hover:shadow-xl transition-all border-none shadow-md">
            <div className="absolute top-0 left-0 w-2 h-full bg-primary" />
            <CardContent className="p-6">
              <div className="flex justify-between items-start">
                <div>
                  <h3 className="text-xl font-bold text-secondary mb-1">{membro.nombre}</h3>
                  <div className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold ${
                    membro.rol === 'admin' ? 'bg-indigo-100 text-indigo-800' : 'bg-primary/20 text-primary-dark'
                  }`}>
                    {membro.rol === 'admin' ? 'Administrador' : 'Operador'}
                  </div>
                </div>
                <div className="w-12 h-12 bg-surface rounded-full flex items-center justify-center text-xl font-bold text-secondary">
                  {membro.nombre.charAt(0).toUpperCase()}
                </div>
              </div>
              
              <div className="mt-6 pt-6 border-t border-border flex justify-end">
                {membro.rol !== 'admin' && (
                  <Button 
                    variant="ghost" 
                    className="text-danger hover:text-danger hover:bg-danger/10 p-0 h-auto px-3 py-1 font-semibold"
                    onClick={() => handleRemove(membro.auth_id, membro.nombre)}
                  >
                    Remover
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      <Sheet open={isSheetOpen} onOpenChange={setIsSheetOpen}>
        <SheetContent className="flex flex-col h-full sm:max-w-md w-full p-0 bg-surface border-l-0 sm:border-l sm:rounded-l-3xl shadow-2xl overflow-y-auto">
          <div className="px-6 py-8 border-b border-border/40 bg-white sticky top-0 z-10">
            <SheetHeader>
              <SheetTitle className="text-2xl font-black text-secondary">Añadir Miembro</SheetTitle>
              <SheetDescription className="text-muted font-medium">
                Crea un acceso para que tu equipo registre almuerzos.
              </SheetDescription>
            </SheetHeader>
          </div>

          <div className="flex-1 px-6 py-8 bg-surface">
            {errorMsg && (
              <div className="mb-6 p-4 bg-danger/10 border-l-4 border-danger rounded-r-xl text-danger text-sm font-medium">
                ⚠️ {errorMsg}
              </div>
            )}

            <form id="equipe-form" onSubmit={handleCreate} className="space-y-6">
              <div className="space-y-2.5">
                <Label htmlFor="nombre" className="text-secondary font-bold">Nombre del Colaborador</Label>
                <Input
                  id="nombre"
                  name="nombre"
                  autoComplete="off"
                  placeholder="Ej. Carlos Mendoza"
                  className="bg-white border-2 border-border/60 focus-visible:border-primary focus-visible:ring-4 focus-visible:ring-primary/10 rounded-xl px-4 py-6 text-lg font-medium transition-all"
                  required
                />
              </div>

              <div className="space-y-2.5">
                <Label htmlFor="email" className="text-secondary font-bold">Correo Electrónico (Login)</Label>
                <Input
                  id="email"
                  name="email"
                  type="email"
                  autoComplete="off"
                  placeholder="carlos@lindamariana.com"
                  className="bg-white border-2 border-border/60 focus-visible:border-primary focus-visible:ring-4 focus-visible:ring-primary/10 rounded-xl px-4 py-6 text-lg font-medium transition-all"
                  required
                />
              </div>

              <div className="space-y-2.5">
                <Label htmlFor="password" className="text-secondary font-bold">Contraseña de Acceso</Label>
                <Input
                  id="password"
                  name="password"
                  type="text"
                  autoComplete="off"
                  placeholder="Mínimo 6 caracteres"
                  className="bg-white border-2 border-border/60 focus-visible:border-primary focus-visible:ring-4 focus-visible:ring-primary/10 rounded-xl px-4 py-6 text-lg font-medium transition-all"
                  required
                  minLength={6}
                />
                <p className="text-xs text-muted">Anota esta contraseña y compártela con tu empleado.</p>
              </div>

              <div className="space-y-2.5">
                <Label htmlFor="rol" className="text-secondary font-bold">Rol en el Sistema</Label>
                <Select name="rol" defaultValue="operador">
                  <SelectTrigger className="w-full bg-white border-2 border-border/60 focus:ring-4 focus:ring-primary/10 rounded-xl px-4 py-6 text-lg font-medium">
                    <SelectValue placeholder="Seleccione Rol" />
                  </SelectTrigger>
                  <SelectContent className="rounded-xl border-border shadow-xl">
                    <SelectItem value="operador" className="focus:bg-primary/10 focus:text-secondary py-3 text-base">Operador (Solo Marcación)</SelectItem>
                    <SelectItem value="admin" className="focus:bg-primary/10 focus:text-secondary py-3 text-base">Administrador (Total)</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </form>
          </div>
          
          <div className="p-6 bg-white border-t border-border/50 mt-auto sticky bottom-0 z-10 sm:rounded-bl-3xl">
            <SheetFooter className="gap-3 sm:gap-0">
              <Button
                variant="outline"
                type="button"
                onClick={() => setIsSheetOpen(false)}
                className="rounded-xl border-2 hover:bg-surface font-bold py-6 px-4"
              >
                Cancelar
              </Button>
              <Button
                type="submit"
                form="equipe-form"
                disabled={isSubmitting}
                className="bg-primary hover:bg-primary-dark text-white rounded-xl shadow-lg shadow-primary/25 font-bold py-6 px-8"
              >
                {isSubmitting ? "Creando..." : "✅ Registrar Miembro"}
              </Button>
            </SheetFooter>
          </div>
        </SheetContent>
      </Sheet>
    </>
  );
}
